import React from 'react'
import Head from 'next/head'

const Headers = () => {
  return (
    <Head>
    <title>NFTInfo</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/nft-blue.png" />
  </Head>
  )
}

export default Headers