import React from 'react'
import { Contact } from '@/exports'
import Head from 'next/head'

const contact = () => {
  
  // The Contact page section, this carries a component that carries a few other contact component
  return (
    <section className='min-h-screen flex items-center w-full'>
         <Head>
        <title>NFTInfo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nft.png" />
      </Head>
      <Contact />
    </section>
  )
}

export default contact