import Image from 'next/image'
import { Inter, Bebas_Neue, Alata, Archivo_Black, Archivo } from 'next/font/google'
import Head from 'next/head'
import { IntroSection, ShortDescriptionSection, OverlayBg, TraverseBlocks } from '@/exports'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  // The Homepage section, this carries some template components, each being a section of the homepage
  // The components are named terribly, trust me, I know
  return (
    <main >
      <Head>
        <title>NFTInfo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nft.png" />
      </Head>
      <section className="flex min-h-screen flex-col items-center justify-between">
      <IntroSection />
      <ShortDescriptionSection />
      <OverlayBg />
      <TraverseBlocks />
      </section>
    </main>
  )
}
