import React from "react";
import { FindNfts } from "@/exports";
import Head from "next/head";

const index = () => {
  return (
    <section className="min-h-screen">
      <Head>
        <title>NFTInfo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nft.png" />
      </Head>
      <FindNfts />
    </section>
  );
};

export default index;
